name = "Qaintmodels"
uuid = "ab7059c2-a49a-4c6e-9904-a72a0109a3ff"
authors = ["Keefe Huang <huangq@in.tum.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Qaintessent = "9e6618a4-6605-11ea-2880-e931cf774ea8"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Qaintessent = "0.1.1"
julia = "1.5, 1.6"

